base_requirements:
  - "remi-release"
php_versions:
  - "php56"
  - "php70"
  - "php71"
  - "php72"
  - "php73"
  - "php74"
  - "php80"
php_base_packages:
  - "php-gd"
  - "php-xml"
  - "php-cli"
  - "php-pdo"
  - "php-gmp"
  - "php-fpm"
  - "runtime"
  - "php-json"
  - "php-snmp"
  - "php-pear"
  - "php-soap"
  - "php-intl"
  - "php-tidy"
  - "php-imap"
  - "php-snmp"
  - "php-devel"
  - "php-xmlrpc"
  - "php-common"
  - "php-bcmath"
  - "php-pspell"
  - "php-snappy"
  - "php-process"
  - "php-mysqlnd"
  - "php-opcache"
  - "php-enchant"
  - "php-mbstring"
php_pecl_modules:
  - "php-pecl-zip"
  - "php-pecl-ssh2"
  - "php-pecl-geoip"
  - "php-pecl-oauth"
  - "php-pecl-redis"
  - "php-pecl-imagick"
  - "php-pecl-igbinary"
  - "php-pecl-memcache"
  - "php-pecl-memcached"
php56_specific_packages:
  - "php-mcrypt"
  - "php-pecl-libsodium"
  - "php-ioncube-loader"
php70_specific_packages:
  - "php-mcrypt"
  - "php-pecl-libsodium"
  - "php-ioncube-loader"
php71_specific_packages:
  - "php-mcrypt"
  - "php-pecl-libsodium"
  - "php-ioncube-loader"
php72_specific_packages:
  - "php-mcrypt"
  - "php-pecl-libsodium"
  - "php-ioncube-loader"
php73_specific_packages:
  - "php-sodium"
  - "php-ioncube-loader"
php74_specific_packages:
  - "php-sodium"
php80_specific_packages:
  - "php-sodium"
