base_requirements:
  - "remi-release"
php_versions:
  - "php56"
  - "php70"
  - "php71"
  - "php72"
  - "php73"
  - "php74"
  - "php80"
  - "php81"
  - "php82"
  - "php83"
  - "php84"
php_base_packages:
  - "php-bcmath"
  - "php-brotli"
  - "php-cli"
  - "php-common"
  - "php-devel"
  - "php-enchant"
  - "php-fpm"
  - "php-gd"
  - "php-gmp"
  - "php-imap"
  - "php-intl"
  - "php-mbstring"
  - "php-mysqlnd"
  - "php-opcache"
  - "php-pdo"
  - "php-pear"
  - "php-pgsql"
  - "php-process"
  - "php-pspell"
  - "php-snappy"
  - "php-snmp"
  - "php-soap"
  - "php-tidy"
  - "php-xml"
  - "php-xmlrpc"
  - "runtime"
php_pecl_modules:
  - "php-pecl-dio"
  - "php-pecl-imagick"
  - "php-pecl-memcache"
  - "php-pecl-memcached"
  - "php-pecl-mongodb"
  - "php-pecl-msgpack"
  - "php-pecl-oauth"
  - "php-pecl-ssh2"
  - "php-pecl-zip"
php56_specific_packages:
  - "php-ioncube-loader"
  - "php-sourceguardian-loader"
  - "php-mcrypt"
  - "php-maxminddb"
  - "php-pecl-libsodium"
  - "php-pecl-redis"
php70_specific_packages:
  - "php-ast"
  - "php-ioncube-loader"
  - "php-sourceguardian-loader"
  - "php-json"
  - "php-mcrypt"
  - "php-maxminddb"
  - "php-pdo-dblib"
  - "php-pecl-libsodium"
  - "php-pecl-redis"
php71_specific_packages:
  - "php-ast"
  - "php-ioncube-loader"
  - "php-sourceguardian-loader"
  - "php-json"
  - "php-mcrypt"
  - "php-maxminddb"
  - "php-pdo-dblib"
  - "php-pecl-libsodium"
  - "php-pecl-redis"
php72_specific_packages:
  - "php-ast"
  - "php-ioncube-loader"
  - "php-sourceguardian-loader"
  - "php-json"
  - "php-mcrypt"
  - "php-maxminddb"
  - "php-pdo-dblib"
  - "php-pecl-igbinary"
  - "php-pecl-redis"
php73_specific_packages:
  - "php-ast"
  - "php-ioncube-loader"
  - "php-json"
  - "php-maxminddb"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-redis"
php74_specific_packages:
  - "php-ast"
  - "php-ioncube-loader"
  - "php-json"
  - "php-maxminddb"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-redis5"
php80_specific_packages:
  - "php-ast"
  - "php-json"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-geoip"
  - "php-pecl-redis5"
php81_specific_packages:
  - "php-ast"
  - "php-json"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-geoip"
  - "php-pecl-redis5"
php82_specific_packages:
  - "php-ast"
  - "php-json"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-geoip"
  - "php-pecl-redis5"
php83_specific_packages:
  - "php-ast"
  - "php-json"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-geoip"
  - "php-pecl-redis5"
php84_specific_packages:
  - "php-ast"
  - "php-json"
  - "php-sodium"
  - "php-pecl-igbinary"
  - "php-pecl-geoip"
  - "php-pecl-redis5"
